---
- name: Login As Super User
  command: "oc login --insecure-skip-tls-verify=true -u {{ admin_user }} -p {{ admin_password }}"
  when: cluster=="openshift"

- name: Change project to {{ namespace }}
  command: "oc project {{ namespace }}"
