---
- include: "login.yml"

- name: Get content metadata
  uri:
    url: "{{ disk_image_url }}"
    method: HEAD
  register: response

- name: Calculate PVC size
  set_fact:
    # Use 4% FS overhead based on this research
    # https://rwmj.wordpress.com/2009/11/08/filesystem-metadata-overhead/
    size_bytes: "{{ (response.content_length|int * 1.04)|int }}"

- name: Build PVC
  template:
    src: cdi-pvc.yml
    dest: /tmp/pvc.yml

- name: Debug generated pvc
  command: cat /tmp/pvc.yml
  register: debug_out
- name: Show generated pvc
  debug:
    msg: "{{ debug_out.stdout }}"

- name: Provision PVC
  command: "oc apply -f /tmp/pvc.yml"

- name: Set pvc_name
  set_fact:
    pvc_name: "{{ vm_name }}-disk-01"

- name: Set disk_bus
  set_fact:
     disk_bus: "{{ disk_bus_by_os_type[os_type] }}"

- name: Set disk_size_bytes
  set_fact:
    disk_size_bytes: "{{ size_bytes }}"

- name: Build VM resources
  template:
    src: "{{ role_path }}/../../templates/{{ os_type }}-{{ image_type }}.j2"
    dest: /tmp/vm-resources.yml

- name: Provision VM resources
  command: "oc apply -f /tmp/vm-resources.yml"
